### ISSUE TITLE
Question on file

### ISSUE THREAD

**Issue by Jester5537** [Metalgearay/YDK2Text-and-Text2YDK#1]
What did you use to create the cards.cbd file????
I can't find a way to open it at all, and I want to see about making a GUI for this, but before i can I want to see about learning everything I can about your project. I know the cbd is a database but nothing I have is able to open it in a user friendly way.

**Comment by Metalgearay** [comment]
The actual database comes from yugo pro itself so if you download the newest version it comes with a new cards.cdb. As for opening up I just wrote a python script to dump the contents via SQL queries so if you want to actuall view it I suggest just dumping the contents of the DB
